# Generated by Django 5.2 on 2025-05-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetraCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('letra', models.TextField(blank=True)),
                ('emocion', models.CharField(blank=True, max_length=50)),
                ('puntaje', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
