# Generated by Django 5.2 on 2025-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letracancion',
            name='portada_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
